print("Ingrese su nombre:")
nombre = input()
print("Ingrese su apellido:")
apellido = input()
print("Ingrese su edad:")
edad = int(input())
print("Por ultimo ingrese su localidad:")
localidad = input()
print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {localidad}.")